url: 


# Site settings
title: Amadea
email: amadea@gmail.com
description: Amadea grožio salono namai. Įvairios grožio procedūros už jums palankią kainą. 

# Build settings
markdown: kramdown
permalink: pretty


sass:
  style: compressed